### PR TITLE
Package transfer

### PR DESCRIPTION
**Pull request by zsteinmetz**
This is my working copy of #13 to prepare the transfer of key functions added here to the Open Specy package repo. See https://github.com/wincowgerDEV/OpenSpecy-package/pull/117 for reference.

PR todos:

- [x] Move new functions to the Open Specy package
- [x] Update Shiny folder structure (https://shiny.rstudio.com/articles/modules.html)
- [x] Revisit config.yml approach; for instance to make ads disappear on a local installation
- [x] Check package dependencies

### CODE REVIEW

**Comment by wincowgerDEV** [comment]
Right on man! Thanks for helping make some headway on this. I'm hoping to get back to the code in a few weeks, for now focusing on developing a new super fast data collection routine

**Comment by wincowgerDEV** [comment]
> * [ ]  Update Shiny folder structure (https://shiny.rstudio.com/articles/modules.html)

Love all these steps you are proposing, wanted to check in about this one though to think through it a little more before we commit. It seems like this would essentially functionalize UI components and server components which is cool but I wonder how much reusability there is for that, like do you think that someone else will want to just have our analysis routine in their app? I see a lot of value in functionalizing the workflows in ways that people can run them in a package without opening the app at all but not totally sure how people would use the UI and server components unless they want to build another shiny app.

**Comment by zsteinmetz** [comment]
> > * [ ]   Update Shiny folder structure (https://shiny.rstudio.com/articles/modules.html)
> 
> Love all these steps you are proposing, wanted to check in about this one though to think through it a little more before we commit. It seems like this would essentially functionalize UI components and server components which is cool but I wonder how much reusability there is for that, like do you think that someone else will want to just have our analysis routine in their app? I see a lot of value in functionalizing the workflows in ways that people can run them in a package without opening the app at all but not totally sure how people would use the UI and server components unless they want to build another shiny app.

I'd say the main advantage of this is that it'll make the code easier to maintain in the long run. So it's mainly for us. The package is more for the users, indeed, to integrate Open Specy into their workflows.

**Comment by wincowgerDEV** [comment]
Oh ok! Sounds good then let's do it! I made a bunch of new ui updates too
btw. Shifting to bs4dash because it's extremely well featured. Going to
start working on the package functions on your branch now.

**Comment by wincowgerDEV** [comment]
> This is my working copy of #13 to prepare the transfer of key functions added here to the Open Specy package repo. See [wincowgerDEV/OpenSpecy-package#117](https://github.com/wincowgerDEV/OpenSpecy-package/pull/117) for reference.
> 
> PR todos:
> 
> * [x]  Move new functions to the Open Specy package
> * [ ]  Update Shiny folder structure (https://shiny.rstudio.com/articles/modules.html)
> * [ ]  Revisit config.yml approach; for instance to make ads disappear on a local installation
> * [ ]  Check package dependencies

I think we will save the modules for a future release, they can be challenging to maintain from people I have talked to about them. I will go through the config and package dependencies before I merge.

**Comment by wincowgerDEV** [comment]
Closing, superceeded

**Pull request closed without merging**
